### PR TITLE
relax upper bound on base to include base-4.8

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks! I assume that you have verified this compiles with 4.8?

**Comment by larskuhtz** [comment]
yes, it does build.

**Comment by jonsterling** [comment]
OK, than I'll merge it. Thanks again!

**Comment by jonsterling** [comment]
Do you need me to make an adjustment now to the metadata on hackage? Or shall we wait for the next release of this library?

**Comment by larskuhtz** [comment]
I think that's a good idea. I forgot that it is now possible. 

It's only needed for GHC 7.10 which is expected to be released in February and many packages already support it GHC 7.10.

**Comment by jonsterling** [comment]
Ok, I have made the adjustment on hackage.

**Pull request merged**
